version: "3.9"
services:
  web:
    container_name: p-web
    image: nginx
    volumes:
      - ./project:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - "8080:80"
  php:
    container_name: p-app
    image: php:8.1.9-fpm-buster
    volumes:
      - ./project:/var/www/html
    entrypoint: ["bash", "-c", "php composer.phar install && php-fpm --nodaemonize"]
